openapi: "3.0.0"
info:
  version: 1.0.0
  title: Express/Open API/Mongoose template
servers:
  - url: http://127.0.0.1:8000
paths:
  /ping:
    get:
      summary: Pings the api
      operationId: ping
      responses:
        '200':
          description: An acknowledgement from the API.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ping:
                    type: string
  /user/login:
    post:
      summary: Authenticates a user and returns a JSON Web Token.
      operationId: login
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/apiUser"
      responses:
        '200':
          description: Returns a valid JWT on successful authentication
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/token"
        '401':
          description: Returns an authentication error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /user/getRoles:
    get:
      security:
        - bearerAuth: []
      summary: Get the roles of the authenticated user. Can be used to test a successful login
      operationId: getRoles
      tags:
        - user
      responses:
        '200':
          description: Some protected data
          content:
            application/json:
              schema:
                type: object
                properties:
                  roles:
                    type: array
                    items: 
                      type: string
components:
  schemas:
    apiUser:
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    token:
      properties:
        token:
          type: string
    error:
      properties:
        error:
          type: string
        details:
          type: array
          items:
            type: string
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT 